stages:
  - setup
  - test
  - teardown

include:
  - https://gitlab.invenia.ca/infrastructure/gitlab-ci-helper/raw/master/templates/hidden-jobs.yml
  - https://gitlab.invenia.ca/infrastructure/gitlab-ci-helper/raw/master/templates/teardown.yml

.awscli_install: &awscli_install
  |
  # Install AWS CLI
  [[ $CI_DISPOSABLE_ENVIRONMENT == "true" ]] && SUDO="" || SUDO="sudo"
  if [[ -x "$(command -v yum)" ]]; then
      # Note: git and gcc is needed to install cloudspy
      ${SUDO} yum -y install python3 python3-devel git gcc
  elif [[ -x "$(command -v apt-get)" ]]; then
      ${SUDO} apt-get -y update
      ${SUDO} apt-get -y install python3 python3-dev python3-venv git
  elif [[ -x "$(command -v brew)" ]]; then
      brew install python || (brew upgrade python && brew cleanup python)
  fi

  python3 -m venv venv
  source venv/bin/activate
  pip install awscli
  python --version
  aws --version

.cloudspy_install: &cloudspy_install
  |
  # Install Cloudspy in the env
  pip install git+https://gitlab-ci-token:${CI_BUILD_TOKEN}@gitlab.invenia.ca/infrastructure/cloudspy.git#egg=cloudspy


"1.0 (Mac)":
  tags:
    - mac
    - shell-ci
  extends: .test_shell_1_0

"1.0 (Linux, 64-bit)":
  tags:
    - linux
    - 64-bit
    - docker-ci
  extends: .test_docker_1_0

"1.0 (Linux, 32-bit)":
  tags:
    - linux
    - 32-bit
    - shell-ci
  extends: .test_shell_1_0

"1.1 (Mac)":
  tags:
    - mac
    - shell-ci
  extends: .test_shell_1_1

"1.1 (Linux, 64-bit)":
  tags:
    - linux
    - 64-bit
    - docker-ci
  extends: .test_docker_1_1

"1.1 (Linux, 32-bit)":
  tags:
    - linux
    - 32-bit
    - shell-ci
  extends: .test_shell_1_1

"Nightly (Mac)":
  tags:
    - mac
    - shell-ci
  extends: .test_shell_nightly

"Nightly (Linux, 64-bit)":
  tags:
    - linux
    - 64-bit
    - docker-ci
  extends: .test_docker_nightly

"Nightly (Linux, 32-bit)":
  tags:
    - linux
    - 32-bit
    - shell-ci
  extends: .test_shell_nightly

"Online Tests":
  tags:
    - linux
    - docker-build
    - shell-ci
  variables:
    LIVE: "true"  # Runs the online S3 tests against AWS
    AWS_DEFAULT_REGION: us-east-1
  before_script:
    - *awscli_install
    - *cloudspy_install
    - curl -sS -o julia-ci https://gitlab.invenia.ca/infrastructure/gitlab-ci-helper/raw/$CI_HELPER_BRANCH/julia-ci
    - chmod +x julia-ci
    - ./julia-ci install $JULIA_VERSION
  script:
    - source julia-ci export
    - export PATH="$PATH:/usr/local/bin"
    - eval $(aws-stack-outputs gitlab-ci-runners)   # Exports the test bucket to work in
    - printenv
    - ./julia-ci test
    - ./julia-ci coverage
  extends: .test_shell_1_0
